version: '3.8'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - playground
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/

  php:
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
      args:
        user: laravel
        uid: 1000
    restart: unless-stopped
    networks:
      - playground
    volumes:
      - ./:/var/www
    working_dir: /var/www/

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    platform: linux/amd64
    networks:
      - playground
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  redis:
      image: redis
      networks:
        - playground
      ports:
        - 6379:6379

  mailhog:
    image: mailhog/mailhog
    networks:
      - playground
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  mysql-data:

networks:
  playground:
    driver: bridge
