version: '3.8'

services:
  nginx:
    container_name: laravel-playground-nginx
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - playground
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/

  php:
    container_name: laravel-playground-php
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
      args:
        user: www-data
    restart: unless-stopped
    networks:
      - playground
    volumes:
      - ./:/var/www
    working_dir: /var/www/

  mysql:
    container_name: laravel-playground-mysql
    image: mysql:5.7
    restart: unless-stopped
    platform: linux/amd64
    networks:
      - playground
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  redis:
    container_name: laravel-playground-redis
    image: redis
    networks:
      - playground
    ports:
      - 6379:6379

volumes:
  mysql-data:

networks:
  playground:
    driver: bridge
