on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via Envoyer
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: 'https://envoyer.io/deploy/OZEEwItiahKt3pvAHkAioLU6o9lUkeGmvEA9RF7P?branch=main'
